### ISSUE TITLE
Unindexed events in BREE_STAKE_FARM

### ISSUE THREAD

**Issue by Arctek** [coinbreeder/coinbreederDAO#1]
Hi,

I would strongly suggest indexing some of the parameters in the events that are emitted, so that these can be easily queried via `eth_getLogs` and event subscriptions.

Especially any of the addresses.

i.e.
`event TokenAdded(address indexed tokenAddress, uint256 indexed APY);`

Thanks.

**Comment by Arctek** [comment]
Looks like some of the line breaks have been broken in the current commit.

Also I would suggest using the same capitalization for the require messages, i.e. 
`"use staking instead"`
`"Use staking instead"`

**Comment by coinbreeder** [comment]
Hey Acrtek!

Thank you for your suggestions we appreciate these input and will implement them accordingly

Eugene

**Comment by coinbreeder** [comment]
Suggestions have been implemented on: https://github.com/coinbreeder/coinbreederDAO/commit/e17b3cfa58a633b7e810876b4547413751fca239
